# Generated by Django 4.2 on 2023-06-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('dob', models.DateField()),
                ('gen', models.CharField(max_length=50)),
                ('stuClass', models.TextField()),
                ('reg', models.TimeField()),
            ],
        ),
    ]
